### ISSUE TITLE
Protected Pebble Tuple

### ISSUE THREAD

**Issue by rastadrian** [pebble/pebble-android-sdk#3]
Is there a reason why the PebbleTuple became protected?

```java
final class PebbleTuple {
    ...
}
```

It makes it hard to implement a generic handler for the dictionaries if I can't access the tuples like we had on the previous versions.

**Comment by sarfata** [comment]
No good reason. We are making it non-final in the next version. It may be a little while before we do a new release. Let us know if this is urgent for you.

Thanks for the feedback.

**Comment by rastadrian** [comment]
My issue is not the `final` actually, but the removal of the `public`. At least for my purpose, I don't require to extend it but to be able to access it and import it. 

It is not urgent for us, you guys provided a JSON getter in the dictionary that we manipulate but the Tuple allows us to have a more object oriented approach/code.

Thanks for the response!

**Comment by sarfata** [comment]
Gotcha. Making it public too!

**Comment by rastadrian** [comment]
@sarfata Thank you! great job on this library by the way.
