### ISSUE TITLE
The link of Sonatype in readme dies

### ISSUE THREAD

**Issue by lydhr** [pebble/pebble-android-sdk#8]
The link of 'Download the pebblekit-3.1.0-eclipse.jar file from Sonatype' doesn't work. Please update it.

**Comment by cjwilliams** [comment]
Thanks for reporting this! It looks like the automated deployment of the 3.1.0 release failed to update the version number in the README link for the 3.1.0 jar. 

With the 4.0.0 release on 11/25, the link was fixed, but if you'd like to still access the 3.1.0 build, you can do so by accessing https://oss.sonatype.org/service/local/repositories/releases/content/com/getpebble/pebblekit/3.1.0/pebblekit-3.1.0-eclipse.jar
